# Makefile

all: linear_search

linear_search: linear_search.cpp arrayUtils.cpp arrayUtils.h
	g++ linear_search.cpp arrayUtils.cpp -o linear_search
binary_search: binary_search.cpp arrayUtils.cpp arrayUtils.h
	g++ binary_search.cpp arrayUtils.cpp -o binary_search

clean:
	rm -f binary_search
